version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: http_server
    ports:
      - "8080:8080"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: http_client
    depends_on:
      - server
